# Generated by Django 2.2.1 on 2019-05-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='username', max_length=100, verbose_name='Customer Name')),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
