# Generated by Django 2.2.1 on 2019-06-02 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='customer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='date',
            field=models.DateField(default=datetime.date(2019, 6, 2)),
        ),
    ]
