# Generated by Django 2.2.1 on 2019-06-08 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20190602_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='date',
            field=models.DateField(default=datetime.date(2019, 6, 8)),
        ),
    ]
